# Generated by Django 3.2 on 2021-06-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_message_contact_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messages',
        ),
    ]
